### ISSUE TITLE
lua line support.

### ISSUE THREAD

**Issue by 0xab3** [horanmustaplot/xcarbon.nvim#1]
hey, i just started using this theme and it matches perfectly with my setup, just wanted to ask if you are willing to add support for lualine.
good work btw.

**Comment by 0xab3** [comment]
my dumbass thought that lua line requires another colorscheme

**Comment by harunnoir** [comment]
> hey, i just started using this theme and it matches perfectly with my setup, just wanted to ask if you are willing to add support for lualine. good work btw.

thx by the way :)
I think I already have lualine support
![image](https://github.com/user-attachments/assets/e0078dfd-a50e-4deb-b614-f72159050a33)
